spring.application.name=api-biblioteca

spring.data.mongodb.uri=mongodb+srv://biblioteca-cluster:biblioteca-cluster@biblioteca-cluster.jdwd5p4.mongodb.net/biblioteca-cluster?appName=biblioteca-cluster

spring.data.mongodb.database=biblioteca-cluster